# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  first-job:
    runs-on: ubuntu-latest
    name: first job
    steps:
      - name: step one
        uses: actions/checkout@v3
      - name: step two
        run: date

  second-job:
    runs-on: windows-latest
    name: second job
    steps:
      - name: first step
        uses: actions/checkout@v3
      - name: second step
        run: "Get-Date"

  third-job:
    name: job three
    runs-on: macos-latest
    needs: [first-job, second-job]
    steps:
      - name: first step
        uses: actions/checkout@v3
      - name: second step
        run: date
